name: Build and Publish
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  VERSION: 1.4.1+1.20.4
  LOADERS: fabric
  RELEASE_NAME: Advanced Locate
  MODRINTH_ID: xX0k30jj
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: Publish (Github/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: "${{env.MODRINTH_ID}}"
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}} ${{env.VERSION}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: "${{env.LOADERS}}"
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

      - name: Discord Webhook
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{env.WEBHOOK_URL}}
          content: "New version available @everyone: [${{env.VERSION}}](https://modrinth.com/mod/advancedlocate/version/${{env.VERSION}})!"
          username: Updates
          avatar-url: https://github.com/K0LALA/AdvancedLocate/blob/fabric-1.21.1/src/main/resources/assets/advancedlocate/icon.png